### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Hunter23071985** [117503445/GoWebDAV#32]
Hello!
Please add the ability to **read settings from the config.ini/json/yaml file**. For example:
```
host: 127.0.0.1
port: 82
path: D:\Test
auth:
  - user: user1
    pass: pass1
    rule: RWD
    sdir: .
  - user: user2
    pass: pass2
    rule: R
    sdir: /ADM
```
This will be convenient for a large number of WebDAV users!
Thanks!
